In [4]:
import pandas as pd
import numpy as np

In [5]:
stations = pd.read_csv("stations.csv")
price = pd.read_csv("price.csv")
occupancy = pd.read_csv("occupancy.csv")
volume = pd.read_csv("volume.csv")
duration = pd.read_csv("duration.csv")
distance = pd.read_csv("distance.csv")
time_df = pd.read_csv("time.csv")
information = pd.read_csv("information.csv")
adj = pd.read_csv("adj.csv")

In [6]:
time_df["datetime"] = pd.to_datetime({
    "year": time_df["year"],
    "month": time_df["month"],
    "day": time_df["day"],
    "hour": time_df["hour"],
    "minute": time_df["minute"],
    "second": time_df["second"]
})

In [7]:
time_df.head()

   month  day  year  hour  minute  second            datetime
0      6   19  2022     0       0       0 2022-06-19 00:00:00
1      6   19  2022     0       5       0 2022-06-19 00:05:00
2      6   19  2022     0      10       0 2022-06-19 00:10:00
3      6   19  2022     0      15       0 2022-06-19 00:15:00
4      6   19  2022     0      20       0 2022-06-19 00:20:00

In [8]:
time_df["timestamp"] = range(
    1,
    len(time_df)+1
)

In [9]:
time_df.head()

   month  day  year  hour  minute  second            datetime  timestamp
0      6   19  2022     0       0       0 2022-06-19 00:00:00          1
1      6   19  2022     0       5       0 2022-06-19 00:05:00          2
2      6   19  2022     0      10       0 2022-06-19 00:10:00          3
3      6   19  2022     0      15       0 2022-06-19 00:15:00          4
4      6   19  2022     0      20       0 2022-06-19 00:20:00          5

In [10]:
price_long = price.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="price"
)

In [11]:
price_long.head()

   timestamp station_id  price
0          1        102  0.924
1          2        102  0.924
2          3        102  0.924
3          4        102  0.924
4          5        102  0.924

In [12]:
occupancy_long = occupancy.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="occupancy"
)

In [13]:
occupancy_long.head()

   timestamp station_id  occupancy
0          1        102         12
1          2        102         12
2          3        102         12
3          4        102         12
4          5        102         12

In [14]:
volume_long = volume.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="volume"
)

In [15]:
duration_long = duration.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="duration"
)

In [16]:
print(price_long.shape)
print(occupancy_long.shape)
print(volume_long.shape)
print(duration_long.shape)

(2134080, 3)
(2134080, 3)
(2134080, 3)
(2134080, 3)

In [17]:
print(price_long.shape)
print(price_long.head())

print(occupancy_long.shape)
print(occupancy_long.head())

(2134080, 3)
   timestamp station_id  price
0          1        102  0.924
1          2        102  0.924
2          3        102  0.924
3          4        102  0.924
4          5        102  0.924
(2134080, 3)
   timestamp station_id  occupancy
0          1        102         12
1          2        102         12
2          3        102         12
3          4        102         12
4          5        102         12

In [18]:
volume_long = volume.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="volume"
)

duration_long = duration.melt(
    id_vars=["timestamp"],
    var_name="station_id",
    value_name="duration"
)

In [19]:
price_long["station_id"] = price_long["station_id"].astype(int)
occupancy_long["station_id"] = occupancy_long["station_id"].astype(int)
volume_long["station_id"] = volume_long["station_id"].astype(int)
duration_long["station_id"] = duration_long["station_id"].astype(int)

In [20]:
master = price_long.merge(
    occupancy_long,
    on=["timestamp", "station_id"]
)

master = master.merge(
    volume_long,
    on=["timestamp", "station_id"]
)

master = master.merge(
    duration_long,
    on=["timestamp", "station_id"]
)

In [21]:
print(master.shape)
master.head()

(2134080, 6)

   timestamp  station_id  price  occupancy    volume  duration
0          1         102  0.924         12  2.858333      0.49
1          2         102  0.924         12  4.375000      0.75
2          3         102  0.924         12  4.375000      0.75
3          4         102  0.924         12  4.375000      0.75
4          5         102  0.924         12  4.375000      0.75

In [22]:
time_df["timestamp"] = range(
    1,
    len(time_df)+1
)

In [23]:
master = master.merge(
    time_df,
    on="timestamp",
    how="left"
)

In [24]:
master.head()

,timestamp,station_id,price,occupancy,volume,duration,month,day,year,hour,minute,second,datetime
0,1,102,0.924,12,2.858333,0.49,6,19,2022,0,0,0,2022-06-19 00:00:00
1,2,102,0.924,12,4.375000,0.75,6,19,2022,0,5,0,2022-06-19 00:05:00
2,3,102,0.924,12,4.375000,0.75,6,19,2022,0,10,0,2022-06-19 00:10:00
3,4,102,0.924,12,4.375000,0.75,6,19,2022,0,15,0,2022-06-19 00:15:00
4,5,102,0.924,12,4.375000,0.75,6,19,2022,0,20,0,2022-06-19 00:20:00

In [26]:
information.head()

,num,station_id,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,1,102,30,3,27,0.71,114.1030,22.54041,0,0
1,3,105,93,0,93,0.77,114.1208,22.55127,0,0
2,5,107,88,2,86,0.89,114.1304,22.54486,0,0
3,6,108,39,0,39,1.26,114.1315,22.55403,0,0
4,7,109,39,0,39,3.15,114.1430,22.56388,0,0

In [27]:
information = information.rename(
    columns={"grid":"station_id"}
)

In [28]:
information["station_id"] = information["station_id"].astype(int)

In [29]:
master = master.merge(
    information,
    on="station_id",
    how="left"
)

In [30]:
master.shape

(2134080, 22)

In [31]:
master.to_csv(
    "master_dataset.csv",
    index=False
)